<?php
    $this->headTitle("Blog");
?>

<h1>Blog</h1>

<p>
    <a href="<?=$this->url('post', ['action' => 'add']); ?>">New Post</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Actions</th>
    </tr>
    <?php foreach ($posts as $post): ?>
        <tr>
            <th><?=$this->escapeHtml($post->title);?></th>
            <th><?=$this->escapeHtml($post->content);?></th>
            <th>
                <a href="<?=$this->url('post', ['action' => 'edit', 'id' => $post->id]); ?>">Edit</a>
                <a href="<?=$this->url('post', ['action' => 'delete', 'id' => $post->id]); ?>">Delete</a>
            </th>
        </tr>
    <?php endforeach; ?>
</table>